name: first-workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
            - name: welcome message
              run: echo "welcome message"

            - name: list file
              run:  ls